{{- range .Values.applications }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argo-cd
spec:
  project: {{ .project }}
  source:
    repoURL: {{ .source.repoURL }}
    path: {{ .source.path }}
    targetRevision: {{ .source.targetRevision }}
    helm:
      valueFiles:
{{- range .source.helm.valueFiles }}
        - {{ . }}
{{- end }}
  destination:
    server: {{ .destination.server }}
    namespace: {{ .destination.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
{{- end }}
